In [1]:
import sys 
sys.path.append("..") 
import autodiff.AD as AD
import autodiff.AD as AD
import numpy as np
import pytest


In [2]:
x = AD.Var([1], [1, 0, 0])
y = AD.Var([2], [0, 1, 0])
z = AD.Var([3], [0, 0, 1])
f = x + y + z

In [3]:
f

Function values:
[6]
Gradient:
[1. 1. 1.]

In [4]:
x+y

Function values:
[3]
Gradient:
[1. 1. 0.]

In [5]:
g = AD.Var([x, y ** 2, z ** 4])

In [6]:
g

Function values:
[ 1.  4. 81.]
Jacobian:
[[  1.   0.   0.]
 [  0.   4.   0.]
 [  0.   0. 108.]]

In [7]:
    x = AD.Var([1, 2, 3], [1, 0, 0])
    y = AD.Var([1, 2, 3], [0, 1, 0])
    z = AD.Var([1, 2, 3], [0, 0, 1])

In [8]:
x + AD.sin(y) + z**2

Function values:
[ 2.84147098  6.90929743 12.14112001]
Derivative values:
[ 1.         -0.41614684  6.        ]

In [9]:
a = AD.Var([3], [1, 0])
b = AD.Var([4], [0, 1])

In [10]:
a - b

Function values:
[-1]
Gradient:
[ 1. -1.]

In [11]:
-AD.Var(3)

Function value:
-3.0
Derivative value:
-1.0

In [12]:
x = AD.Var([3.0], [1, 0])
y = AD.Var([2], [0, 1])
z = x * y


In [13]:
z.der == np.array([2.0, 3.0])

array([ True,  True])

In [14]:
x = AD.Var([3.0], [1, 0, 0])
y = AD.Var([1.0], [0, 1, 0])
w = AD.Var([2.0], [0, 0, 1])
z = (x + y ** 2 + x * w)/2

In [15]:
x = AD.Var(3.0)
a = AD.Var([ 1., x, x, 4.])

In [16]:
x = AD.Var([2.0, 3], [1,1])

In [17]:
AD.log(x, 2)

Function values:
[1.        1.5849625]
Derivative values:
[0.72134752 0.48089835]

In [18]:
x = AD.Var([3, 1, 0.3])
y = AD.Var(3)

In [19]:
x**y

Function values:
[[2.7e+01 1.0e+00 2.7e-02]]
Jacobian:
[[27.          3.          0.27      ]
 [29.66253179  0.         -0.03250727]]

In [21]:
x = AD.Var([2])
AD.logistic(x)

Function values:
[0.88079708]
Derivative values:
[0.10499359]