In [1]:
import sys 
sys.path.append("..") 
import autodiff.AD as AD
import autodiff.AD as AD
import numpy as np
import pytest


In [13]:
x = AD.Var([np.pi/4])
y = AD.tan(x)

In [14]:
y.val

array([1.])

In [23]:
np.array_equal(y._der, [2*np.tan(np.pi/4)])

True

In [16]:
np.array_equal(y._val, [np.tan(np.pi/4)])

True

In [17]:
[np.tan(np.pi/4)]

[0.9999999999999999]

In [10]:
np.array_equal([1.],[1])

True

In [20]:
z = np.linspace(0, 1, 100)
u = AD.Var(z)
v = AD.sin(u)

In [21]:
np.array_equal(v._val, np.sin(z))

True

In [2]:
x = AD.Var([1], [1, 0, 0])
y = AD.Var([2], [0, 1, 0])
z = AD.Var([3], [0, 0, 1])
f = x + y + z

In [3]:
f

Function values:
[6]
Gradient:
[1. 1. 1.]

In [4]:
x+y

Function values:
[3]
Gradient:
[1. 1. 0.]

In [5]:
g = AD.Var([x, y ** 2, z ** 4])

In [6]:
g

Function values:
[ 1.  4. 81.]
Jacobian:
[[  1.   0.   0.]
 [  0.   4.   0.]
 [  0.   0. 108.]]

In [7]:
    x = AD.Var([1, 2, 3], [1, 0, 0])
    y = AD.Var([1, 2, 3], [0, 1, 0])
    z = AD.Var([1, 2, 3], [0, 0, 1])

In [8]:
x + AD.sin(y) + z**2

Function values:
[ 2.84147098  6.90929743 12.14112001]
Derivative values:
[ 1.         -0.41614684  6.        ]

In [9]:
a = AD.Var([3], [1, 0])
b = AD.Var([4], [0, 1])

In [10]:
a - b

Function values:
[-1]
Gradient:
[ 1. -1.]

In [11]:
-AD.Var(3)

Function value:
-3.0
Derivative value:
-1.0

In [12]:
x = AD.Var([3.0], [1, 0])
y = AD.Var([2], [0, 1])
z = x * y


In [13]:
z.der == np.array([2.0, 3.0])

array([ True,  True])

In [14]:
x = AD.Var([3.0], [1, 0, 0])
y = AD.Var([1.0], [0, 1, 0])
w = AD.Var([2.0], [0, 0, 1])
z = (x + y ** 2 + x * w)/2

In [15]:
x = AD.Var(3.0)
a = AD.Var([ 1., x, x, 4.])

In [16]:
x = AD.Var([2.0, 3], [1,1])

In [17]:
AD.log(x, 2)

Function values:
[1.        1.5849625]
Derivative values:
[0.72134752 0.48089835]

In [18]:
x = AD.Var([3, 1, 0.3])
y = AD.Var(3)

In [19]:
x**y

Function values:
[[2.7e+01 1.0e+00 2.7e-02]]
Jacobian:
[[27.          3.          0.27      ]
 [29.66253179  0.         -0.03250727]]

In [21]:
x = AD.Var([2])
AD.logistic(x)

Function values:
[0.88079708]
Derivative values:
[0.10499359]

In [25]:
x1=AD.Var([0])
x2=AD.Var([5])
f = AD.exp(x1) + x2

In [26]:
f

Function values:
[6.]
Derivative values:
[2.]

In [27]:
x1=AD.Var([10])
x2=AD.Var([5])
f = AD.log(x1) + AD.log(x2)

In [28]:
f

Function values:
[3.91202301]
Derivative values:
[0.3]

In [29]:
    x = AD.Var([5.0])
    y = AD.exp(x, 2)

In [33]:
np.array_equal(y._der, [np.power(2, 5)*np.log(2)])

True

In [34]:
    x = AD.Var([3.0]) 
    y = AD.log(x, 2)

In [35]:
y

Function values:
[1.5849625]
Derivative values:
[0.48089835]

In [36]:
1/(3*np.log(2))

0.48089834696298783

In [37]:
np.array_equal(y._der, 1/(3*np.log(2)))

False

In [40]:
y._der[0] == 1/(3*np.log(2))

True

In [41]:
np.array_equal(y._val, np.log(3)/np.log(2))

False