In [23]:
import sys 
sys.path.append("..") 
import autodiff.AD as AD
import autodiff.AD as AD
import numpy as np
import pytest


In [24]:
x = AD.Var([1], [1, 0, 0])
y = AD.Var([2], [0, 1, 0])
z = AD.Var([3], [0, 0, 1])
f = x + y + z

In [25]:
f

Function:
[6]
Gradient:
[1. 1. 1.]

In [26]:
x+y

Function:
[3]
Gradient:
[1. 1. 0.]

In [27]:
g = AD.Var([x, y ** 2, z ** 4])

In [28]:
g

Function:
[ 1.  4. 81.]
Jacobian:
[[  1.   0.   0.]
 [  0.   4.   0.]
 [  0.   0. 108.]]

In [29]:
    x = AD.Var([1, 2], [1, 0, 0])
    y = AD.Var([1, 2], [1, 0, 0])
    z = AD.Var([1, 2], [0, 1, 0])

In [30]:
x.__eq__(y)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()