In [1]:
import sys 
sys.path.append("..") 
import autodiff.AD as AD
import autodiff.AD as AD
import numpy as np
import pytest


In [2]:
x = AD.Var([1], [1, 0, 0])
y = AD.Var([2], [0, 1, 0])
z = AD.Var([3], [0, 0, 1])
f = x + y + z

In [13]:
f

Function values:
[6]
Gradient:
[1. 1. 1.]

In [4]:
x+y

Function values:
[3]
Gradient:
[1. 1. 0.]

In [5]:
g = AD.Var([x, y ** 2, z ** 4])

In [6]:
g

Function values:
[ 1.  4. 81.]
Jacobian:
[[  1.   0.   0.]
 [  0.   4.   0.]
 [  0.   0. 108.]]

In [7]:
    x = AD.Var([1, 2], [1, 0, 0])
    y = AD.Var([1, 2], [1, 0, 0])
    z = AD.Var([1, 2], [0, 1, 0])

In [8]:
x == y

True

In [15]:
a = AD.Var([3], [1, 0])
b = AD.Var([4], [0, 1])

In [27]:
a - b

Function values:
[-1]
Gradient:
[ 1. -1.]

In [18]:
-AD.Var(3)

Function value:
-3.0
Derivative value:
-1.0

In [20]:
x = AD.Var([3.0], [1, 0])
y = AD.Var([2], [0, 1])
z = x * y


In [26]:
z.der == np.array([2.0, 3.0])

array([ True,  True])

In [30]:
x = AD.Var([3.0], [1, 0, 0])
y = AD.Var([1.0], [0, 1, 0])
w = AD.Var([2.0], [0, 0, 1])
z = (x + y ** 2 + x * w)/2

In [45]:
x = AD.Var(3.0)
a = AD.Var([ 1., x, x, 4.])

In [47]:
3 / a

TypeError: float() argument must be a string or a number, not 'Var'