In [1]:
import matplotlib.pyplot as plt
import numpy as np
import AD

In [2]:
AD.Var(1)

Function value:
1.0
Derivative value:
1.0

In [3]:
x = AD.Var([np.pi/2], [1, 0, 0])
y = AD.Var([3], [0, 1, 0])
z = AD.Var([-2], [0, 0, 1])

In [4]:
4*x

Function value:
6.283185307179586
Gradient:
[4. 0. 0.]

In [5]:
f = AD.Var([AD.sin(x), 4*y + z**3, 3])
f

Function values:
[1. 4. 3.]
Jacobian:
[[6.123234e-17 0.000000e+00 0.000000e+00]
 [0.000000e+00 4.000000e+00 1.200000e+01]
 [0.000000e+00 0.000000e+00 0.000000e+00]]

In [6]:
x = AD.Var(np.pi/4)
AD.tan(x)

Function value:
1.0
Derivative value:
2.0

In [7]:
AD.sin(x)

Function value:
0.7071067811865475
Derivative value:
0.7071067811865476

In [8]:
y = AD.Var(np.sin(x.val), np.cos(x.der))
y

Function value:
0.7071067811865475
Derivative value:
0.5403023058681398

In [9]:
x

Function value:
0.7853981633974483
Derivative value:
1.0

In [10]:
AD.Var(1., 2.)

Function value:
1.0
Derivative value:
2.0

In [11]:
a = np.asarray(np.pi/2).astype(float)
x = AD.Var(a)

In [12]:
x = AD.Var(np.pi/2)
AD.sin(x)

Function value:
1.0
Derivative value:
0.0

In [13]:
AD.sin(AD.Var(np.pi))

Function value:
0.0
Derivative value:
-1.0

In [14]:
float(np.pi)

3.141592653589793

In [15]:
AD.Var(1, 2)

Function value:
1.0
Derivative value:
2.0

In [16]:
x = AD.Var(0, [1, 0])
y = AD.Var(5, [0, 1])
AD.exp(x) + y

Function value:
6.0
Gradient:
[1. 1.]

In [17]:
AD.exp(x)+AD.sin(4*y)

Function value:
1.9129452507276277
Gradient:
[1.         1.63232825]

In [18]:
AD.Var(3, [1, 2])

Function value:
3.0
Gradient:
[1. 2.]

In [19]:
AD.tan(AD.Var(np.pi/4))

Function value:
1.0
Derivative value:
2.0

In [20]:
x = AD.Var(1, [1, 0, 0])
y = AD.Var(2, [0, 1, 0])
z = AD.Var(3, [0, 0, 1])
f = x + y + z
g = 2*x + x*y

In [21]:
g

Function value:
4.0
Gradient:
[4. 1. 0.]

In [22]:
AD.Var([2*x + x*y, -4*x*y])

Function values:
[ 4. -8.]
Jacobian:
[[ 4.  1.  0.]
 [-8. -4. -0.]]

In [23]:
g = AD.Var([AD.sin(4*x*y), -4*x*z, 2])
g

Function values:
[  0.98935825 -12.           2.        ]
Jacobian:
[[ -1.16400027  -0.58200014  -0.        ]
 [-12.          -0.          -4.        ]
 [  0.           0.           0.        ]]

In [24]:
np.array_equal(g.der, [[8*np.cos(8), 4*np.cos(8), 0], [-12, 0, -4], [0, 0, 0]])

True

In [25]:
8*np.cos(8), 4*np.cos(8)

(-1.1640002704689083, -0.5820001352344542)

In [26]:
1 == [1, 2]

False

In [27]:
np.array_equal(1, [1, 2])

False

In [28]:
x = AD.Var(1)
y = AD.Var(2)

In [29]:
x

Function value:
1.0
Derivative value:
1.0

In [30]:
y

Function value:
2.0
Derivative value:
1.0

In [31]:
x == y

False

In [32]:
type(x.val), type(x.der), type(np.ones(1)), type(np.asarray(1.))

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [33]:
x = AD.Var(1, [1, 0, 0])
y = AD.Var(2, [0, 1, 0])
z = AD.Var(3, [0, 0, 1])
x + y + z

Function value:
6.0
Gradient:
[1. 1. 1.]

In [34]:
f = AD.Var([x, y**2, z**4])
f

Function values:
[ 1.  4. 81.]
Jacobian:
[[  1.   0.   0.]
 [  0.   4.   0.]
 [  0.   0. 108.]]

In [35]:
for item in np.nditer(f.der):
    print(item, np.round(item))

1.0 1.0
0.0 0.0
0.0 0.0
0.0 0.0
4.0 4.0
0.0 0.0
0.0 0.0
0.0 0.0
108.0 108.0


In [36]:
for item in f.val:
    print(item)

1.0
4.0
81.0


In [37]:
x = AD.Var([1, 2, 3], [1, 0, 0])
y = AD.Var([4, 5, 6], [0, 1, 0])
x+y

Function values:
[5. 7. 9.]
Derivative values:
[1. 1. 0.]

In [38]:
z = x+y
-z

Function values:
[-5. -7. -9.]
Derivative values:
[-1. -1. -0.]

In [39]:
x = AD.Var(3.0) 
y = AD.log(x)
z = AD.log(x, 2)

In [40]:
y

Function value:
1.0986122886681098
Derivative value:
0.3333333333333333

In [41]:
z

Function value:
1.5849625007211563
Derivative value:
0.48089834696298783

In [42]:
z.val == np.log(3)/np.log(2)

True

In [43]:
z.der == 1/(3*np.log(2))

True

In [44]:
AD.sin(AD.Var(np.pi/2))

Function value:
1.0
Derivative value:
0.0

In [45]:
np.cos(np.pi/2)

6.123233995736766e-17

In [46]:
def test_iter(x):
    try:
        for item in x._val:
            print(item)
        
        for item in np.nditer(x._der):
            print(item)
            
    except TypeError:
        print(x.val, x.der)

In [47]:
test_iter(f)

1.0
4.0
81.0
1.0
0.0
0.0
0.0
4.0
0.0
0.0
0.0
108.0


In [48]:
test_iter(AD.Var(1))

1.0 1.0


In [49]:
test_iter(AD.Var(1, [1, 0]))

1.0 [1. 0.]


In [50]:
a = AD.Var(1)
a.val.size, a.der.size

(1, 1)

In [51]:
x = AD.Var(np.pi/4)
y = AD.tan(x)
y

Function value:
1.0
Derivative value:
2.0

In [52]:
type(y.val), type(y.der)

(numpy.float64, numpy.float64)

In [53]:
z = np.linspace(0, 1, 100)
u = AD.Var(z)
v = AD.sin(u)

In [54]:
np.array_equal(v.val, np.sin(z)), np.array_equal(v.der, np.cos(z))

(True, True)

In [55]:
np.array(2) == 2

True

In [56]:
np.array(4)

array(4)

In [57]:
a = np.asarray([1, 1.3, 0.9999999999999])

In [58]:
if abs(a-np.round(a)) < 1e-8:
    a = np.round(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()