In [1]:
import matplotlib.pyplot as plt
import numpy as np
import AD

In [2]:
AD.Forward(1)

Function value:
1.0
Derivative value:
1.0

In [3]:
x = AD.Forward([np.pi/2], [1, 0, 0])
y = AD.Forward([3], [0, 1, 0])
z = AD.Forward([-2], [0, 0, 1])

In [4]:
4*x

Function:
[6.28318531]
Gradient:
[4. 0. 0.]

In [5]:
f = AD.Forward([AD.sin(x), 4*y + z**3])
f

Function:
[1. 4.]
Jacobian:
[[ 0.  0.  0.]
 [ 0.  4. 12.]]

In [8]:
x = AD.Forward([np.pi/4])
AD.tan(x)

Function values:
[1.]
Derivative values:
[2.]

In [ ]:
x.val, x.der

In [ ]:
x

In [ ]:
AD.sin(x)

In [ ]:
y = AD.Forward(np.sin(x.val), np.cos(x.der))

In [ ]:
x

In [ ]:
AD.Forward(1., 2.)

In [ ]:
a = np.asarray(np.pi/2).astype(float)
x = AD.Forward(a)

In [ ]:
AD.sin(x)

In [14]:
AD.sin(AD.Forward([np.pi]))

Function values:
[0.]
Derivative values:
[-1.]

In [16]:
float(np.pi)

3.141592653589793