In [1]:
import matplotlib.pyplot as plt
import numpy as np
import AD

In [2]:
AD.Forward(1)

Function value:
1.0
Derivative value:
1.0

In [3]:
x = AD.Forward([np.pi/2], [1, 0, 0])
y = AD.Forward([3], [0, 1, 0])
z = AD.Forward([-2], [0, 0, 1])

In [4]:
4*x

Function:
[6.28318531]
Gradient:
[4. 0. 0.]

In [5]:
a = [AD.sin(x), 4*y + z**3, 3]
vals = []
jac = []

for element in a:
    try:
        vals.append(element._val)
        jac.append(element._der)
    except AttributeError:
        vals.append([element])
        jac.append(np.zeros(len(a)))

vals = np.asarray(vals).astype(float).flatten()
vals

array([1., 4., 3.])

In [6]:
jac = np.asarray(jac).astype(float)
jac

array([[ 0.,  0.,  0.],
       [ 0.,  4., 12.],
       [ 0.,  0.,  0.]])

In [7]:
f = AD.Forward([AD.sin(x), 4*y + z**3, 3])
f

Function:
[1. 4. 3.]
Jacobian:
[[ 0.  0.  0.]
 [ 0.  4. 12.]
 [ 0.  0.  0.]]

In [8]:
x = AD.Forward([np.pi/4])
AD.tan(x)

Function values:
[1.]
Derivative values:
[2.]

In [9]:
x.val, x.der

(array([0.78539816]), array([1.]))

In [10]:
x

Function values:
[0.78539816]
Derivative values:
[1.]

In [11]:
AD.sin(x)

Function values:
[0.70710678]
Derivative values:
[0.70710678]

In [12]:
y = AD.Forward(np.sin(x.val), np.cos(x.der))

In [13]:
x

Function values:
[0.78539816]
Derivative values:
[1.]

In [14]:
AD.Forward(1., 2.)

Function value:
1.0
Derivative value:
2.0

In [15]:
a = np.asarray(np.pi/2).astype(float)
x = AD.Forward([a])

In [16]:
AD.sin(x)

Function values:
[1.]
Derivative values:
[0.]

In [17]:
AD.sin(AD.Forward([np.pi]))

Function values:
[0.]
Derivative values:
[-1.]

In [18]:
float(np.pi)

3.141592653589793